include:  
  - component: $CI_SERVER_FQDN/TECH_Team/ci/secrets-detection/secrets-detection@2.1.1
  - component: $CI_SERVER_FQDN/TECH_Team/ci/trust/trust@2.0.0-4
  - component: $CI_SERVER_FQDN/TECH_Team/ci/python-pipeline/python@1.2.0